---
chapter: 3
knit: "bookdown::render_book"
---

# Data


## Factor analysing

To better understand the reason of fire ignition, it is important to find out factors that could contribute the fire. Besides of the location of fires, season of fire, topogrphic infomation and weather information are also contributes to the development of fire. and distance to road, and fire bridgade can also help distinguish the reasons of fires.As a result, we need to obtain those related information from reliable sources.



##  Data collection


Several historic fire spot data are from JAXA’s Himawari-8 satellite which allows us to investigate the location, development and potential sources of fire ignition. The historical weather data are downloaded from the Bureau of Meteorology with the help of R package "bomrang". While detailed historical fire origin data, CFA fire station location data and VIC recreation site location data are sourced from Victorian Government open data. the Forest data we used in the fire prediction model  are from Forests of Australia (2018). and the Near-Surface Wind Speed data in the prediction model are from CSIRO.



##  Data construction

To find out the weather detail of the fire spot at the time and in short past, the coordinates of the fires was used to matching with its nearest Weather station. However, some historical data for newly constructed stations are unavailable. To solve such problem, the nearest 10 weather stations were matched with each fire spot before finding out the possible historical data. After fusing the fire, weather and forest datasets, other data like distance to campsite, CFA station and roads are calculated and added for each fire.



