---
chapter: 5
knit: "bookdown::render_book"
---

# The App desgin

One of the outcomes of the project is an interactive shiny app to allow others to explore bushfire location and intensity data. With this app, users could locate the historical fires with related information, compare conditions of fires caused by different reasons, explore the probability for different area for typical ignition causes and  continue further analysis of the fire data. The target user of the shiny app would be researchers, local goverments, fire brigades. For reasearchers, with our dedicated data construction, they can continue the analysis of the relationship between different factors and provide adivices for policy reforms that help improve forest management. For local goverments and fire brigades, this app could help them better understand historical fire and know what would be the fire ignition reason in different season under different climate condition for specific area. 


## Tab 1 - The main page

In this tab, we would like to provide our users insight of the overall historical fires on an interactive map. When designing the app, we provide an interactive map with multivariate fire data for the ease of our users. With this map, they can easily compare historical fires across Victoria on the map based on the  information they provide. To distingish fires ignited by 6 different reasons on the map, we assign different colours for each ignition reason. The interactive map of historical fire data is on centre of the main page. By the selection of different year, month and ignition reason, fires are filtered and shown on victoria map, and users can not only compare the number of fires for a specific period but the time and spatial distribution for ignition reason.


For the purpose of comparing fires happened in different year ranges and having an clear view of fires ignited by different reason across the state by different years, we design a Year Slider Input for users to switch the year range between 1990 to 2019. By sliding the year input, users could select from one specific year to 19 years fire data and each time the the Slider moves, the fire shown on the map will change accordingly and automatically. Users could compare the distribution of fires in different years by simply change one side of the input or move the whole slide bar.


In different season, fire prevention regulation may change. For example, from late October to April, most city councils would announce burning off restrictions, which would largely reduce the fires caused by human burning off in this period. Besides, the Mediterranean climate brings wet and cold weather to Victoria between May and August. As a result, fires for any reason would be less likely happening in these months. To help users compare the distribution of fires in different months, we design a check box for a month input. Each time the user could choose a single or multipal months, the map will only shown fires happened in a specific month, and users could choose multiple month to combine 


To compare the distribution of fires with a specific reason is often of the most interest for users. We provide a check box to allow users to choose the fires caused by the reason(s) they are interested to shown on the map. After invstigating the historical data, we classify the ignition reasons into 6 categories, accident, arson, burning off, lightning, relight, other reason. Users can select either one or more ignition reason at once. So they can just have a clear view and understanding of one reason caused fires by choose one reaseon or compare the distribution of locations for different fires by choose multiple options at once. Fires from different reasons are plotted by different colours based on the colour selection principle by Claus O. Wilke(Fundamentals of Data Visualization). Once the users select the cause in the left side penal, the fire will shown accordingly. As Arson or lighting are always the topic of debates regarding to Bushfire, we need to stress these two kinds of fires on the map. Because the background of the map is light green, we allocation two outstading colours black and dark blue for the ease of users especially someone with color vision deficiency like me.


By clicking each fire point, related information would pop up on the map, and the weather condition on the day that fire happened and 14 and 28 day average before the fire would shown on the right handside of the penal.  With 20 year average weather condition for the specific time as bench mark, we could find the weather deviation for fire time and figure out whether any weather condition have a higher possibility for a specific ignition reason. The interactive plotting below the weather chart reflect the trend of fire number over years and the change of ignition reasons for fires in different time.


In addition, buttons to show and clear the density plot for fires are provided. Users could show the density of fire which matches the conditions they have selected on the map. Due to the limitation of Shiny app, the density plot cannot be updated automaticly for each time users change their fire condition selection. So they have to click clear and show button to refresh the density plot.  


To help users have a better understanding of the distribution of the total number to fires for each reason, there is an interactive chart on the right side penal. It shows the total number of fires according to each year. Similar to the map, we allocate each reason a colour to distinguish them. On the chart above, users can easily compare the total number of fires. To comppare the total numbers fires cuased by selected reasons in each year, users can click the legend of the chart above, then a time series of fire for the reason selected will be plotted on the chart below. Users can see the change of the trend of the specific kind of fire between 1990 to 2019. 


## Tab 2 - Ignition reason prodicted map


The second page of the app is our prediction model for 2019 October to 2020 March, ie, the 2019-2020 fire season. On this map the locations of fire are caught by the satelite, while the reason of such fires are not fully investigated yet, we use our predction model with the satelite data to predict the reasons of such fires happend in 2019-2020. Similar with the main page, we design a checkbox to allow user to choose the ignition reason and a checkbox to select the month, range between October 2019 and March 2020. In our prediction model, we claasify the possible reason into 4 categories: accident, arson,burning off and lightning. Once the user has chosen the month and igniton reason, the fire with predicted reason will be plotted on the map automatically with different colours for each reason. Similar to the main page, the map is interactive. By clicking the fire spot, users can obtain the information for the fire like, longitude, latitude,forest type, distance to road. The temperature and artificial precipitation infomation of the time the fire happened will shown on the right panel as well to allow users to compare.



## Tab 3 - Fire probability map.

The third page of the app is fire probability map based on random forest model and historical data. On this map, we devide Victioria in to 25 x 25 grids. By doing so, a Like other maps in our shiny app, it comes with chechboxed to allow the users to choose any month in the fire season and the ignition reason that they are interested. The map will update automatically with the change of users selection. As metioned above, in the probability map, we divide Victoria into a 25 X 25 grid that allow users to know the probability of fire for their selected ingniton reason and time. By doing so, residents will have much clear idea of the possible fire of their local area and be aware in advance; government users and researchear could clearly find out the probability distribution of bushfires across Victoria for each reason by different season.  Moreover when user click a specific area on the map, the related information for each grid will pop up.


## Tab 4 - Interactive Data

This page is an interactive database mainly for professional users. On this page there are collumns including EventID, Firename, Fire district, Fire start date, Longitue, Latitude, Forest Type , Forest Category and Cause. For each collumn, we allow users to sort the data with figure order or alphatetic order. For collumn with number content, to fast filter data, users can use slide button to select range they want. Besides, we provide a search box to allow users fast locate a specific event with key words.  Moreover, to accomodate users' different screen sizes, we provide an droplist button with the option 10,25,50,100 to allow users to choose show number of entries they want shown per page.




