---
chapter: 4
knit: "bookdown::render_book"
---

# Methodology

## Spatial-statistical analysis 

Firstly, for each ignition type of fire, a patial investigation was conducted with both incident rate and kernel denstiy for each type of fire. The incident rate was compared based on the fires happened in each grid over 20 years which help identify the area that has most fires, while the kernal density for each type of fire help us find out the spatial concentration of ignition reason. When a specify type of rarely occured in selected time, the density mapping may not be accurate. While the incident number increases, the density plot provide a direct and clear view of the distribution for each type of fire. That is why kernal density plot is a popular visualisation method where the volume of incidents are relatively large and spatially clustered (Brunsdon, Corcoran, & Higgs, 2007; Chainey, 2002; Ratcliffe, 2000). This plot distinguishes areas of high concentration of specific fire (indicated by darker colours) from area with lower concentrations (indicated by lighter or no colour). The approach is calculated by passing a kernel of a set of bandwidth across a specific area that includes the number of fires for a given ignition reason that fall within the area of the kernel. So the size of the area of the kernel is the denominator and the number of fires in each kernel is the numerator. We assgin the larger calculated result a darker colour and a lighter colour for the smaller result.

The most important parameter that controls the smoothness of the density estimate plot is the choice of bandwidth. A very low bandwidth values will lead density estimates to be rough, where each fire incident will be shown on the map rather than combine incidents nearby to form cluster of fires, while a too high bandwidth wiill draw too many contour lines on the map and thus thus makes it hard to distinguish areas with different density. The selection of an optimum bandwidth has been the focus for many studies (Bowman, 1984; Bowman & Azzalini, 1997; Silverman, 1986). The most effective method is to try different bandwidths and choose the one giving the output neither too rough nor too smoothed. After some trials, a bandwidth value of 0.15 was the best for all scenarios in this project.



## Fire prediction model and visualisation of fire probability

Our analysis consisted of assesing the fires happened between the years 1990 and 2019 across the state of Victoria. According to many reseachers like Abdi & Kamkar(2016), Stratton(2006), there are several considerations for spatialfire analysis in different categories: 1 Landscape Considerrations: Forest crown cover, forest height class;2 Land Fire History: fire occurrence,fire progression;3 Ecological Considerations:  Forest types and category, water bodies; 4 Socio-economic Considerations: camps, historic and recreational sites, roads; 5 Weather Considerations: wind and precipitation. 


Jennings (1999) concluded that ecological approaches "provide a valuable framework for discussing and enumerating the factors contributing to the fire problem. This approach has been applied with considerable precedent and offers great promise for understanding more fully the socio-economic determinants of the fire problem." In our fire probability prediction model, we have included socio-economic variables, weather variables in geographic context. In particular, first, we divided the Victria map into grids, and using the fire prediction model with 55 variables to calculate the probability of fires ignited by different reasons in each grid. This probability is calculated based on the assumption that there is fire happened in each grid, $p(r|f)$. Second, using 20 year data, we calculated the probability of fire happening for each grid $p(f)$. Third, based on Bayesian equation, we could get the joint probability for each fire reason and fire happened in that grid $p(r,f)$.

$$ p(r,f) = p(r|f) *p(f) $$
Our main result is a proposed method to visualise probability of fire for the combination of specific reason and month using pixelation. The map of Victoria is triangle-like, with longitude ranging from $140.6923$ to $149.8976$ and latitude ranging from $-34.03690$ to $-39.08246$. In the begining, we need to decide the size of a grid. If we choose a small grid size, precision for historical fire distribution and visual quality of the map may increased, however there are less fires fall into each gird, requiring a higher workload and lead to a decreasing the average probability per grid. Thus ther would be larger areas on the map with zero fire probability and the realibility of our prediction would be quit low. However, if the size of each grid is too large, there would be too many fires in each grid, though it will increase the precision of our prediction model, the realibility of the probability mapping would be low, and we cannot use it for a specific small area and the user of the app cannot it to warn fires happend in their local ares. A suitable resolution for each grid that each grid contains a area with size covers a local fire brigade working range. So we divide the Victoria map into $25$ x $25$ grids and thus balance the precision and practical dilemma.

## The test of uncertainty




